# Generated by Django 2.1.4 on 2019-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.FloatField(null=True),
        ),
    ]
