# Generated by Django 2.1.7 on 2019-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190214_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='model_solution',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
